repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        exclude: ^(modules/|dockerfiles/)
      - id: pretty-format-json
        args: ["--autofix"]
        exclude: "Pipfile.lock"
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: no-commit-to-branch
        args: ["--branch", "main"]
