apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-webhook
  labels:
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/name: knative-operator
subjects:
  - kind: ServiceAccount
    name: operator-webhook

roleRef:
  kind: Role
  name: knative-operator-webhook
  apiGroup: rbac.authorization.k8s.io
