apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: knative-operator-webhook
  labels:
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/name: knative-operator
rules:
  # For manipulating certs into secrets.
  - apiGroups:
      - ""
    resources:
      - "secrets"
    verbs:
      - "get"
      - "create"
      - "update"
      - "list"
      - "watch"
      - "patch"
