apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-operator
  labels:
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/name: knative-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-webhook
  labels:
    app.kubernetes.io/version: "1.13.0"
    app.kubernetes.io/name: knative-operator
